version: 2
updates:
- package-ecosystem: composer
  target-branch: "stable3"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies

- package-ecosystem: composer
  target-branch: "stable3"
  directory: "/vendor-bin/cs-fixer/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies

- package-ecosystem: npm
  target-branch: "stable3"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies

- package-ecosystem: github-actions
  target-branch: "stable3"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
